modLoader="javafml"
license="LGPL"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Trins-mods/PlayerAbiityLib-forge/issues"

[[mods]]
modId="playerabilitylib"
version="${version}"
displayName="Pal"
displayURL="https://github.com/Trins-mods/PlayerAbiityLib-forge"
credits="Pyrofab for the original PlayerAbilityLib."
authors="Trinsdar, Pyrofab"
description='''Your good pal, helping with mod compat'''
[[dependencies.playerabilitylib]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.34,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.playerabilitylib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="AFTER"
    side="BOTH"
